inputs:
  pytest-options:
    description: "Extra options to pass to Pytest"
    default: ''
runs:
  using: "composite"
  steps:
  - name: Install apt dependencies
    shell: bash -l {0}
    run: |
      sudo apt update
      sudo apt install xvfb libqt5x11extras5 libgl1-mesa-glx '^libxcb.*-dev'
  - name: Install RasCAL2
    shell: bash -l {0}
    run: pip install .
  - name: 
    shell: bash -l {0}
    run:  pytest -s tests/ ${{ inputs.pytest-options }} --cov=rascal2 --cov-report=term
