# Workflow file for slow tests & on multiple python versions
name: Integration tests
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:  # <-- can be triggered manually!

jobs:
  integration-tests:
    if: github.event.review.state == 'approved'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: [3.10, 3.11, 3.12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python version ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install package and requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .
      - name: Run pytest
        run: conda run pytest -s tests/ -m "not slow" --cov=rascal2 --cov-report=term
