# Workflow file for fast unit tests which run on all commits
name: Unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          
  unit-tests:
    name: Unit tests
    needs: ruff  # avoid wasting CI time if static analysis failed
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4      
      - name: Set up Conda environment from environment.yaml
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          auto-activate-base: false
      - name: Install and run tests (Linux)
        if: runner.os == 'linux'
        uses: ./.github/actions/linux
        with:
          pytest-options: '-m "not slow"'
      - name: Install and run tests (MacOS)
        if: runner.os == 'macos'
        uses: ./.github/actions/macos
        with:
          pytest-options: '-m "not slow"'
      - name: Install and run tests (Windows)
        if: runner.os == 'windows'
        uses: ./.github/actions/windows
        with:
          pytest-options: '-m "not slow"'

