# Workflow file for fast unit tests which run on all commits
name: Unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff format --check
          
  unit-tests:
    name: Unit tests
    needs: ruff  # avoid wasting CI time if static analysis failed
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda environment from environment.yaml
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          auto-activate-base: false
      - name: Install and run tests (Linux)
        if: runner.os == 'linux'
        uses: ./.github/actions/linux
        with:
          pytest-options: '-m "not slow"'
      - name: Install and run tests (MacOS/Windows)
        if: runner.os != 'linux'
        uses: ./.github/actions/windows-mac

